### ISSUE TITLE
Problem when run in production

### ISSUE THREAD

**Issue by tinngv** [expressmapper/ExpressMapper#68]
I'm change from Automapper to ExpressMapper and got a problem.

Deploy on 4 server. After change to ExpressMapper, all their cpus & their rams increase to much. It make web request response to slow (20 ~ 100s)

IIS7.5 + ASP.NET MVC 4 + ExpressMapper
Concurrent User: 200

**Comment by anisimovyuriy** [comment]
Dear tinngv,

Thanks for choosing Expressmapper and for your input!
Let me ask you couple of questions:
1) What version of Expressmapper do you use?
2) Do you have mapping registration?
3) if you have mapping registration are they called only once on Application_Start?
4) Are you sure that you specified all mapping registrations?

Looking forward to hearing from you!

**Comment by tinngv** [comment]
1. Expressmapper version="1.7.0" from Nuget
2. My register class like this
 public static class Map
    {
       
        public static void Boot()
        {         
            
            ExpressMapper.Mapper.RegisterCustom<byte[], string>(src => src.ToBase64());            

            ExpressMapper.Mapper.RegisterCustom<string, byte[]>( src => src.ToByte());
         
            ExpressMapper.Mapper.Register<AlbumCollection, AlbumModel>()
               .Function(dest => dest.OrderDate, m =>
                {
                    
                        return m.OrderDate.ToShortDateString() + ' ' + m.OrderDate.ToShortTimeString();
                    
                });
			
			//...and more
         }   
	}
}

3.I put it in Application_Start 
{
       Map.Boot();
}

4. All of objects mapping in my code are using ExpressMapper.

**Comment by anisimovyuriy** [comment]
Dear tinngv,

Sounds almost good. Let me try to give you some ideas for improvement and some other questions.

```
  public static void Boot()
  {         

      ExpressMapper.Mapper.RegisterCustom<byte[], string>(src => src.ToBase64());            

      ExpressMapper.Mapper.RegisterCustom<string, byte[]>( src => src.ToByte());

      ExpressMapper.Mapper.Register<AlbumCollection, AlbumModel>()
         .Function(dest => dest.OrderDate, m =>
          {

                  return m.OrderDate.ToShortDateString() + ' ' + m.OrderDate.ToShortTimeString();

          });

      //...and more
   } 
```

I'd rather change your particular registration to:
```
  public static void Boot()
  {         

      ExpressMapper.Mapper.RegisterCustom<byte[], string>(src => src.ToBase64());            
      ExpressMapper.Mapper.RegisterCustom<string, byte[]>( src => src.ToByte());
      ExpressMapper.Mapper.Register<AlbumCollection, AlbumModel>()
         .Member(dest => dest.OrderDate, m =>
                  string.Format("{0} {1}", m.OrderDate.ToShortDateString(), m.OrderDate.ToShortTimeString())
);
      //...and more
   } 
```
As ```.Member``` is much faster than ```.Function``` as ```.Function``` is compiled to ```Func<>``` and being called every time inside of the compiled mapping whereas ```.Member``` is part of the compiled mapping code. But of course it gives you some boost but it's not the issue here I think. 
Before to make another test I'd rather suggest that you  precompile everything which means to cache compiled code as right now first time it is compiled and cached and check if you have all registrations in place.

Questions:
1) Use ```.Compile``` and ```.PrecompileCollection``` after registrations in your ```.Boot``` method. You can read more about pre-compilation <a href="http://expressmapper.org/#plans">here</a>.
2) Do you use "dynamic mapping" - without registrations? - if so please register them
3) Could you please send an example of your code when you actually map one type to another?
4) Could you tell me the difference in percentage or some real figures CPU and Memory before and after using Expressmapper?

Thanks a lot for your input!

Looking forward to hearing from you,
Yuriy

**Comment by tinngv** [comment]
Dear anisimovyuriy,
Sorry for the late reply,

Thanks for your suggestion and improvement in my code. Here is my answer:

1. Applied
2. Yes -> then I updated
3. My map very complex, it's about salesorder, this object contains many salesorder details, customers and products.
4. I re-build the code and deploy again (actually with some tweak from you). It's work very fast now

The problem when convert automapper to expressmapper
AutoMapper with default mapping from null array will return an empty array instead null. I think this should add this features to ExpressMapper.

**Comment by anisimovyuriy** [comment]
Dear tinngv,

Thanks a lot for your response and I'm very happy that it worked out for you.
Let me think about about "Null to Empty array" - could you close this question and create new one for "Null to Empty array"?

Thanks a lot,
Yours Yuriy
