### ISSUE TITLE
MapNotImplementedException no longer thrown on compile

### ISSUE THREAD

**Issue by bzuillsmith** [expressmapper/ExpressMapper#82]
In 1.7.0, I would get ```MapNotImplementedException``` if I forgot to include a type in my mapping or ignore a property and then ran ```mapper.Compile()```. Now in 1.8.0, I no longer get that exception and ```.map()``` copies references if I haven't set my mapping correctly. Is that intended? I would consider that a breaking change. I nearly didn't catch the issue. It was only because I wrote some unit tests that I found the issue so quickly.

**Comment by bzuillsmith** [comment]
Actually, the copying-by-reference issue doesn't seem related to the exception. Perhaps I'm doing something wierd in my code. Still investigating.

**Comment by anisimovyuriy** [comment]
Dear @bzuillsmith,

Thanks for your question.
Actually since [1.5 release](https://github.com/expressmapper/ExpressMapper/releases/tag/1.5) there was  "Dynamic mapping support" introduced. Which implies that if you did not register mapping, it would try to register it during runtime. See documentation [here](http://expressmapper.org/#plans).

Thanks!

**Comment by bzuillsmith** [comment]
Interesting. So was it intended to change the behavior between 1.7 and 1.8?

**Comment by anisimovyuriy** [comment]
Not I'm aware of :)

**Comment by anisimovyuriy** [comment]
@bzuillsmith would you mind to provide some example to clarify uncertainties?
